name: Build KalLPPSA Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install project dependencies
        run: npm install

      - name: Add Android platform
        run: cordova platform add android

      - name: Build Android APK
        run: cordova build android --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: KalLPPSA-APK
          path: platforms/android/app/build/outputs/apk/release/*.apk
